### ISSUE TITLE
Locale problem with date

### ISSUE THREAD

**Issue by Rikysonic** [dorianim/mrbs-docker#4]
Hello, I'm trying your project, everything is working except the date format. I have the locale set in Italian, but I also tested other languages, the date is always shown as following screenshot
![image](https://github.com/dorianim/mrbs-docker/assets/56199646/a8ac2271-884f-4b1d-90ea-8f226d1dd9f0)

I've also tested the original [Dockerfile](https://github.com/meeting-room-booking-system/mrbs-code/blob/main/docker_app/php/Dockerfile) from the mrbs project (adding locales manually with ```RUN apt-get install -y locales locales-all```) and it is working fine.
![image](https://github.com/dorianim/mrbs-docker/assets/56199646/13ca4608-46dc-49e0-b048-43b932212e82)

**Comment by dorianim** [comment]
Oh, I haven't noticed that. Looks like there has been a change to how alpine distributes the locales: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.16.0#ICU_data_split

I'm working on it :)
