### ISSUE TITLE
504 gateway

### ISSUE THREAD

**Issue by sidgaabriel** [dorianim/mrbs-docker#5]
I'm having some issues when I'm trying to create or delete some itens in sequence, nginx cannot handle and give me an 504 gateway Time-out, I tried to increase php and nginx timeout execution but didn't worked for me. Usually happens when I'm using smtp to send an email after nginx become unresponsive and give me the gateway error. 

![20-10-2023-14-05-57](https://github.com/dorianim/mrbs-docker/assets/45013403/79fc5260-f21b-4ca6-b5f0-61a3cc7a8fbe)

**Comment by dorianim** [comment]
This usually happens when the php execution fails with an error.
Can you post the contents of the php logfile?

**Comment by sidgaabriel** [comment]
php log from /mrbs/log/php presents no issues, there's other log file for me to check it?

**Comment by dorianim** [comment]
The right logfile is `mrbs/log/nginx/error.log`

**Comment by sidgaabriel** [comment]
Here's the correct log file, I forced the behavior and you can check the last lines
[error.log](https://github.com/dorianim/mrbs-docker/files/13115116/error.log)

**Comment by dorianim** [comment]
Hmm, looks like the edit_entry.php takes too long to finish. I don't think this is related to the docker container. But please also post your config so I can double check.

**Comment by sidgaabriel** [comment]
Here's my docker-compose.yml
[docker-compose.yml.zip](https://github.com/dorianim/mrbs-docker/files/13116310/docker-compose.yml.zip)

**Comment by dorianim** [comment]
I meant the config.php, sorry.

**Comment by sidgaabriel** [comment]
No problem, here's the file.
[config.inc.php.zip](https://github.com/dorianim/mrbs-docker/files/13121202/config.inc.php.zip)

**Comment by dorianim** [comment]
I guess, the error is caused by your email configuration. Maybe the server is not responding or taking too long to respond. However, I don't think, this is related to the docker container.

Please open an issue in the MRBS project.
