### ISSUE TITLE
Company Logo

### ISSUE THREAD

**Issue by flex420** [dorianim/mrbs-docker#8]
Hello folks , had  no luck changing the company logo with this docker version of mrbs. is that a known issue? 

having that in  the config.inc.php:

$mrbs_company_logo = "logo.png";

The File itself is as "logo.png" in the mbrs root directory on the host (./config/mrbs/logo.png) but cant get it to load. Any hint's for me? 

Kind regards
flx

**Comment by dorianim** [comment]
To set the icon, please put it into `./config/mrbs/www/assets/logo.png` and use `$mrbs_company_logo = "assets/logo.png";` in the configuration.

**Comment by flex420** [comment]
perfect- that worked flawlessly! Thank you VERY much! Just installed it and trying to configuring everything as needed for the shop for me wife ;)
