### ISSUE TITLE
Suggestion to Upgrade Docker Container to PHP 8.3

### ISSUE THREAD

**Issue by cecilyen** [dorianim/mrbs-docker#9]
I wanted to share an article I found that shows some impressive performance improvements in PHP 8.3 over PHP 8.1. According to the [PHP Benchmarks: Real-World Speed Tests for Versions 8.1, 8.2, and 8.3](https://kinsta.com/blog/php-benchmarks/), PHP 8.3 is significantly faster.

Would you consider upgrading your MRBS container to PHP 8.3? I think this upgrade could really boost MRBS's performance.

**Comment by cecilyen** [comment]
PHP 8.3 is available from Alpine 3.19 onward.

**Comment by dorianim** [comment]
Thanks for the suggestion. I pinned the image while back, because the newer ones didn't support armv7:
https://github.com/dorianim/mrbs-docker/commit/448e912e1b577c6be0748475d44d67afec6536a3

I think the reasoning was that armv7 is needed for older raspberry pis.

**Comment by cecilyen** [comment]
Support for Alpine 3.17 will end in four months on November 22, 2024. It may be time to consider upgrading to Alpine 3.19 or later.

**Comment by dorianim** [comment]
Alright, I've dropped armv7 support and upgraded to alpine 3.20 with php 8.3 in (1.11.5)(https://github.com/dorianim/mrbs-docker/releases/tag/v1.11.5)
